# Kong Gateway Configuration
# operator-996 Platform API Gateway

_format_version: "3.0"

services:
  # Main API Service
  - name: operator996-api
    url: http://operator996-api.operator996.svc.cluster.local:3000
    protocol: http
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    retries: 5
    routes:
      - name: api-root
        paths:
          - /api
        strip_path: true
        protocols:
          - http
          - https
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
        plugins:
          - name: rate-limiting
            config:
              minute: 100
              hour: 5000
              policy: local
          - name: cors
            config:
              origins:
                - "*"
              methods:
                - GET
                - POST
                - PUT
                - DELETE
                - PATCH
                - OPTIONS
              headers:
                - Accept
                - Authorization
                - Content-Type
                - X-Request-ID
              exposed_headers:
                - X-Request-ID
                - X-RateLimit-Limit
                - X-RateLimit-Remaining
              credentials: true
              max_age: 3600
          - name: request-id
            config:
              header_name: X-Request-ID
              echo_downstream: true
          - name: jwt
            config:
              key_claim_name: kid
              secret_is_base64: false
              claims_to_verify:
                - exp
          - name: request-transformer
            config:
              add:
                headers:
                  - X-Gateway:Kong
                  - X-Forwarded-For:$remote_addr
          - name: response-transformer
            config:
              add:
                headers:
                  - X-Response-Time:$upstream_response_time

  # Biofeedback Service
  - name: biofeedback-service
    url: http://biofeedback.operator996.svc.cluster.local:3001
    routes:
      - name: biofeedback-api
        paths:
          - /biofeedback
        strip_path: false
        plugins:
          - name: rate-limiting
            config:
              minute: 60
              hour: 1000
          - name: jwt

  # Analytics Service
  - name: analytics-service
    url: http://analytics.operator996.svc.cluster.local:3002
    routes:
      - name: analytics-api
        paths:
          - /analytics
        strip_path: false
        plugins:
          - name: rate-limiting
            config:
              minute: 30
              hour: 500
          - name: jwt

plugins:
  # Global Plugins
  - name: prometheus
    config:
      status_code_metrics: true
      latency_metrics: true
      bandwidth_metrics: true
      upstream_health_metrics: true

  - name: correlation-id
    config:
      header_name: X-Correlation-ID
      generator: uuid
      echo_downstream: true

  - name: ip-restriction
    config:
      allow:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
      status: 403
      message: "Access denied from your IP"

  - name: bot-detection
    config:
      allow:
        - googlebot
        - bingbot
      deny:
        - curl
        - wget
        - scrapy

upstreams:
  - name: operator996-upstream
    algorithm: round-robin
    hash_on: none
    hash_fallback: none
    healthchecks:
      active:
        healthy:
          interval: 10
          successes: 2
        unhealthy:
          interval: 5
          http_failures: 3
          tcp_failures: 3
          timeouts: 3
        http_path: /health
        timeout: 1
      passive:
        healthy:
          successes: 3
        unhealthy:
          http_failures: 5
          tcp_failures: 2
          timeouts: 3
    targets:
      - target: operator996-api.operator996.svc.cluster.local:3000
        weight: 100
